### ISSUE TITLE
dpkg object fails this check

### ISSUE THREAD

**Issue by erikarasnick** [geomarker-io/codec#104]
https://github.com/geomarker-io/codec/blob/cdc8d1867178a91d782a1cfe71afd9c26b78a9b8/R/codec_dpkg_s3.R#L18

I think `(!inherits(x, "dpkg::dpkg"))` would work

**Comment by cole-brokamp** [comment]
I changed the class of dpkg objects from `dpkg::dpkg` to `dpkg` when I changed to using the S3 system instead of S7 in the dpkg package.  Are you using the latest version?
