### ISSUE TITLE
add OUD deserts?

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/codec#115]
https://zenodo.org/records/4011051

does this have variability in Hamilton County?

**Comment by cole-brokamp** [comment]
yes, should have enough

**Comment by erikarasnick** [comment]
![Image](https://github.com/user-attachments/assets/1496763d-e14e-4b6c-b2a4-03b8315d6e92)

not a ton of variability for hamilton county... also not sure how frequently treatment centers are opened/closed. We published this paper in 2021.
