### ISSUE TITLE
create releases for upstream data repos

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/codec#66]
Keeping a description is good, but I don't think they will be used in the codec data catalog, nor the exlorer.  Even though we won't use them right here, we should still create releases (with assets) for each of these updated TDRs.

- [ ] https://github.com/geomarker-io/hamilton_property_code_enforcement
- [ ] https://github.com/geomarker-io/hamilton_drivetime
- [ ] https://github.com/geomarker-io/hamilton_traffic
- [ ] https://github.com/geomarker-io/hamilton_landcover
- [x] https://github.com/geomarker-io/hh_acs_measures -> `v1.1.0`
- [ ] https://github.com/geomarker-io/tract_indices

Once these are complete, update versions in {codec} and refresh all data.

**Comment by erikarasnick** [comment]
Since none of the actual data was changing, I uploaded the new `.yaml` file with the description to each of the existing releases. Will that work?

**Comment by cole-brokamp** [comment]
I think we accidentally put `codec_data` in the root of the package instead of the `inst` folder.  The functions read in data from `inst` folder, so it still is missing the description field.  For example,

```r
glimpse_attr(cd$hamilton_traffic)
#> # A tibble: 6 × 2
#>   name     value                                       
#>   <chr>    <chr>                                       
#> 1 profile  tabular-data-resource                       
#> 2 name     hamilton_traffic                            
#> 3 path     hamilton_traffic.csv                        
#> 4 version  0.1.0                                       
#> 5 title    Hamilton County Parcel and Household Traffic
#> 6 homepage https://geomarker.io/hamilton_traffic       
```

I also want to update the release for any change we make to the core data repos and make sure that the data is linked with the release assets.  It could be problematic to retroactively change anything with a released TDR without updating with a new release.  If you already changed those, I think its okay -- we should make a new release for each one anyway.

**Comment by cole-brokamp** [comment]
Maybe you ran `/inst/make_codec_data.R` from `codec/` instead of `codec/inst/`?

For each of the scripts, we could change

```r
write_tdr_csv(d, "codec_data")
```

to

```r
write_tdr_csv(d, fs::path_package("codec", "codec_data"))
```

to prevent that from happening.

**Comment by erikarasnick** [comment]
I thought we had made changes to the tdr on the releases before when we were making minor changes that didn't change the data, but that was before we had fully incorporated the core datasets into the codec package. There were other things we needed to update with each data set (e.g., changing the column names from `census_tract_id` to `census_tract_id_2010`) but it felt like we were trying to avoid making minor changes and releasing new versions. But I can go through and make new releases for each one, no problem. 

I didn't realize the descriptions weren't added.. I will change that code and rebuild after creating the new releases for each dataset.

**Comment by cole-brokamp** [comment]
Yeah, you're right.  I think it wouldn't be worth it to regenerate a release for each one.  I did for `hh_acs_measures` because of the other fixes we wanted to do.  I'll rerun the data in the package now that I understand how you updated it.
