### ISSUE TITLE
check_codec fails to find where metadata is present without a corresponding column of data

### ISSUE THREAD

**Issue by andrew-vancil** [geomarker-io/codec#83]
I'm having trouble using interpolate in the codec data explorer. When I try to run `cincy::interpolate`, going from tract to zcta, I get an error for mismatched rows: `Warning: Error in [[<-.data.frame: replacement has 0 rows, data has 54 `

However, when I try to go from tract to neighborhood, I get a slightly different, but similar error: 
```
Error in `structure()`:
! Assigned data `value` must be compatible with existing data.
✖ Existing data has 81 rows.
✖ Assigned data has 0 rows.
ℹ Only vectors of size 1 are recycled.
Caused by error in `vectbl_recycle_rhs_rows()`:
! Can't recycle input of size 0 to size 81.
```

Here's a reprex:
```
library(codec)
library(dplyr)

d_indices <- codec_data("tract_indices", geography = cincy::tract_tigris_2010, geometry = TRUE) |> 
  sf::st_as_sf() |>
  sf::st_transform(crs = 5072) |> 
  select(-year) 

d_interpolated <- cincy::interpolate(from = d_indices, 
                            #to = cincy::neigh_cchmc_2010,
                            to = cincy::zcta_tigris_2010,
                            weights = "pop")
```

**Comment by cole-brokamp** [comment]
If this bug is still present in updates that fix the missing tract_indices data, then hold off on any updates until new {fr} package is implemented.

**Comment by andrew-vancil** [comment]
It appears that using updated `codec` and `cincy` is now working in the explorer app as intended
